changelog/Models/ChangeLogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using changelog.dal;

namespace changelog.Models
{
    public class ChangeLogModel
    {
        public IEnumerable<db_projects> _db_projects { get; set; }
        public IEnumerable<db_Author> _db_author { get; set; }
        public IEnumerable<db_reviewers> _db_reviewers { get; set; }
    }
}

changelog/Controllers/ChangeLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using changelog.Models;
using changelog.dal;
 
namespace changelog.Controllers
{
    public class ChangeLogController : Controller
    {
        //
        // GET: /ChangeLog/

        public ActionResult index()
        {
            ChangeLogModel model = new ChangeLogModel { 
                _db_author = new db_ChangeLog().getProjectsAuthorView()
            };
            return View(model);
        }

        public ActionResult project(int id)
        {
            string sTitleProject = "";
            switch (id)
            {
                case 1: sTitleProject = "Журнал проекта AVIAV3"; break;
                case 2: sTitleProject = "Журнал проекта #2"; break;
                case 3: sTitleProject = "Журнал проекта #3"; break;
                default: sTitleProject = "Проект не известен"; break;
            }
            ViewBag.TitleProject = sTitleProject;

            //ChangeLogModel model = new ChangeLogModel
            //{
            //    _db_projects = new db_ChangeLog().getProjectsView(id)
            //};

            return View();
        }

        public ActionResult GetData(int pageIndex, int pageSize)
        {  
            return Json(new db_ChangeLog().getProjectsView(Convert.ToInt32(Request.QueryString["id"]), pageIndex, pageSize), JsonRequestBehavior.AllowGet);
        }
    }
}

changelog/Views/ChangeLog/index.cshtml
@model changelog.Models.ChangeLogModel

@{
    ViewBag.Title = "Просмотр логирования";
    Layout = "~/Views/Shared/_ChangeLog.cshtml";
}

<!-- PRELOADER -->
<div class="spn_hol">
    <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
    </div>
</div>
<!-- END PRELOADER -->
@Html.Partial("~/Views/partial/_header.cshtml")

<!-- =========================
     START ABOUT US SECTION
============================== -->


<section class="about page" id="ABOUT">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!-- ABOUT US SECTION TITLE-->
                <div class="section_title">
                    <h2>Проекты логирования</h2>
                    <p>Просмотр комментариев и историю изменений</p>
                </div>
            </div>

        </div>
    </div>
    <div class="inner_about_area">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="about_phone wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".5s">
                        <img width="466px" src="~/resources/images/git.png" />
                    </div>
                </div>
                <div class="col-md-6  wow fadeInRight" data-wow-duration="1s" data-wow-delay=".5s">
                    <!-- TITLE -->
                    <div class="inner_about_title">
                        <h2>Журнал <b>проекта    </b></h2>
                        <p>Ниже проекты .</p>
                    </div>
                    <div class="inner_about_desc">

                        <!-- SINGLE DESC -->
                        <div class="single_about_area fadeInUp wow" data-wow-duration=".5s" data-wow-delay="1s">
                            <!-- ICON -->
                            <div><i class="pe-7s-timer"></i></div>
                            <!-- HEADING DESCRIPTION -->
                            <h3><a href="ChangeLog/project?id=1">Проект AVIAV3</a></h3>
                            <p>Авиабронирование</p>
                        </div>
                        <!-- END SINGLE DESC -->
                        <!-- SINGLE DESC -->
                        <div class="single_about_area fadeInUp wow" data-wow-duration=".5s" data-wow-delay="1.5s">
                            <!-- ICON -->
                            <div><i class="pe-7s-target"></i></div>
                            <!-- HEADING DESCRIPTION -->
                            <h3><a href="ChangeLog/project?id=2">Проект #2</a></h3>
                            <p>О проекте #2</p>
                        </div>
                        <!-- END SINGLE DESC -->
                        <!-- SINGLE DESC -->
                        <div class="single_about_area fadeInUp wow" data-wow-duration=".5s" data-wow-delay="2s">
                            <!-- ICON -->
                            <div><i class="pe-7s-stopwatch"></i></div>
                            <!-- HEADING DESCRIPTION -->
                            <h3><a href="ChangeLog/project?id=3">Проект #3</a></h3>
                            <p>О проекте #3</p>
                        </div>
                        <!-- END SINGLE DESC -->

                    </div>
                </div>
            </div>
        </div>
    </div>

    <br />
</section>
<!-- End About Us -->

@Html.Partial("~/Views/partial/_testimonial.cshtml")

changelog/Views/ChangeLog/project.cshtml
@{
    ViewBag.Title = "Журнал проектов";
    Layout = "~/Views/Shared/_ChangeLog.cshtml";
}


 <div id="HOME">
    </div>

    <section class="about page" id="ABOUT">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <!-- ABOUT US SECTION TITLE-->
                    <div class="section_title">
                        <h2>@ViewBag.TitleProject</h2>
                    </div>
                </div>

            </div>
        </div>
        <div class="inner_about_area">
            <div class="container">
                <div class="row">

                    <div id="container"></div>
                    <div id="progress" style="display:none">
                        <h4>Loading...</h4>
                    </div>

                </div>
            </div>
        </div>

    </section>
    <!-- End About Us -->

    <script src="~/Scripts/jquery-3.2.1.min.js"></script>

    <script type="text/javascript">

        var pageSize = 2;
        var pageIndex = 0;

        $(document).ready(function () {
            GetData();

            $(window).scroll(function () {

                if ($(window).scrollTop() ==
                   $(document).height() - $(window).height()) {
                    GetData();
                }
            });
        });

        function GetData() {

            var sContainer = "";

            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetData", "ChangeLog")',
                data: { "pageindex": pageIndex, "pagesize": pageSize },
                dataType: 'json',
                success: function (data) {
                    if (data != null) {

                        for (var i = 0; i < data.length; i++) {

                            sContainer =
                                 "<div class=\"col-md-6\">"
                                    + "<div class=\"about_phone wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\".5s\">"
                                         + "<img src=\"" + data[i].AuthorAvatarUrl + "\">"
                                         + "<br /> <h2>" + data[i].AuthorDisplayName + "</h2>"
                                         + "<h4>"
                                             + "<a target=\"_blank\" href=\"mailto:\"" + data[i].AuthorEmailAddress + "?subject=Уважаемая(ый) " + data[i].AuthorDisplayName + "><span>Написать письмо</span></a> "
                                             + " | "
                                             + "<a target=\"_blank\" href=\"" + data[i].AuthorLinks + "\">Профиль пользователя</a>"
                                         + "</h4>"
                                      + "</div>"
                                  + "</div>"
                                  + "<div class=\"col-md-6  wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\".5s\">"

                                      + "<div class=\"inner_about_desc\">"
         + "<h3> <small>Номер пулла:</small>  " + data[i].id + "</h3>"
                                         + "<div class=\"single_about_area fadeInUp wow\" data-wow-duration=\".5s\" data-wow-delay=\"1s\">"
                                             + "<h3> "
                                             + "<br> <small>Название пулла:</small> " + data[i].title
                                             + "<br> <small>Дата изменения:</small> " + data[i].updatedDate
                                             + "<br> <small>Описание:</small> </h3>"
                                             + "<p> " + data[i].descriptionAsHtml + "</p>"
                                         + "</div>"

                                         + "<br /><h3><strong>Аудиторы:</strong></h3><br />";

                            if (data[i].Reviewers == null) {
                                sContainer += "<span>Не определены</span>";
                            }
                            else {
                                for (var j = 0; j < data[i].Reviewers.length; j++) {
                                    sContainer += "<h3><img src=" + data[i].Reviewers[j].AuthorAvatarUrl + ">"
                                               + data[i].Reviewers[j].AuthorDisplayName
                                              + "<br />"
                                                    + "<small> <a target=\"_blank\" href=\"mailto:\"" + data[i].Reviewers[j].AuthorEmailAddress + "?subject=Уважаемая(ый) " + data[i].Reviewers[j].AuthorDisplayName + "><span>Написать письмо</span></a>"
                                                    + " | "
                                                    + " <a target=\"_blank\" href=\"" + data[i].Reviewers[j].AuthorLinks + "\">Профиль пользователя</a></small>"
                                                + " </h3>"
                                }
                            }

                            sContainer += "</div>"
                                    + " </div> <hr> ";

                            $("#container").append(sContainer);
                        }
                        pageIndex++;
                    }
                },
                beforeSend: function () {
                    $("#progress").show();
                },
                complete: function () {
                    $("#progress").hide();
                },
                error: function () {
                    alert("Error while retrieving data!");
                }
            });

        }

    </script>

changelog/Views/Shared/_ChangeLog.cshtml
<!DOCTYPE html>

<html>
<!--
    ChangeLog - проект по отображению логов
    Site: changelog.corteos.ru
-->


<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Partial("~/Views/partial/_head.cshtml")
    
</head>
<body>


    <div>
        @RenderBody()
    </div>

    @Html.Partial("~/Views/partial/_footer.cshtml")
    @Html.Partial("~/Views/partial/_script.cshtml")
    
</body>
</html>

changelog/Views/partial/_footer.cshtml
<!-- =========================
     FOOTER
============================== -->

<section class="copyright">
    <h2></h2>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="copy_right_text">
                    <!-- COPYRIGHT TEXT -->
                    <p>Copyright &copy; 2017. All Rights Reserved.</p>
                    <p> <a href="http://corteos.ru">Сorteos</a></p>
                </div>

            </div>

            <div class="col-md-6">
                <div class="scroll_top">
                    <a href="#HOME"><i class="fa fa-angle-up"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END FOOTER -->

changelog/Views/partial/_head.cshtml
<meta name="keywords" content="ChangeLog - проект по отображению логов" />
<meta name="description" content="ChangeLog - внутренний портал" />
<meta name="author" content="pechkaytis arunas" />

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
 
<!-- Google Font -->
<link href='https://fonts.googleapis.com/css?family=Raleway:500,600,700,800,900,400,300' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic' rel='stylesheet' type='text/css'>
<!-- Bootstrap -->
<link href="~/resources/css/bootstrap.min.css" rel="stylesheet">
 
<!-- Owl Carousel Assets -->
<link href="~/resources/css/owl.carousel.css" rel="stylesheet">
<link href="~/resources/css/owl.theme.css" rel="stylesheet">


<!-- Pixeden Icon Font -->
<link rel="stylesheet" href="~/resources/css/Pe-icon-7-stroke.css">

<!-- Font Awesome -->
<link href="~/resources/css/font-awesome.min.css" rel="stylesheet">


<!-- PrettyPhoto -->
<link href="~/resources/css/prettyPhoto.css" rel="stylesheet">

<!-- Favicon -->
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

<!-- Style -->
<link href="~/resources/css/style.css" rel="stylesheet">

<link href="~/resources/css/animate.css" rel="stylesheet">
<!-- Responsive CSS -->
<link href="~/resources/css/responsive.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

changelog/Views/partial/_header.cshtml
<!-- =========================
     START HEADER SECTION
============================== -->

<section class="header parallax home-parallax page" id="HOME">
    <h2></h2>
    <div class="section_overlay">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="~/resources/images/corteos-logo.png" alt="" />
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <!-- NAV -->
                        <li><a href="#HOME">Главная</a> </li>
                        <li><a href="#ABOUT">Проекты </a> </li>
                        @*<li><a href="#FEATURES">FEATURES</a></li>
                        <li><a href="#SCREENS">SCREENS</a> </li>
                        <li><a href="#DOWNLOAD">DOWNLOAD </a> </li>
                        <li><a href="#CONTACT">CONTACT </a> </li>*@
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container- -->
        </nav>

        <div class="container home-container">
            <div class="row">
                <div class="col-md-12">
                    <div class="logo text-center">
                        <!-- LOGO --> 
                        <img src="~/resources/images/corteos-logo.png" alt="" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-sm-8">
                    <div class="home_text">
                        <!-- TITLE AND DESC -->
                        <h1>Система управления деловыми поездками</h1>
                        <p>B2B система online-бронирования.</p>

                        <div class="download-btn">
                            <!-- BUTTON -->
                            <a class="btn home-btn wow fadeInLeft" href="#DOWNLOAD">Загрузить</a>
                            <a class="tuor btn wow fadeInRight" href="#ABOUT">Список проектов <i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-md-offset-1 col-sm-4">
                    <div class="home-iphone"> 
                        <img src="~/resources/images/corteos-screen.png" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- END HEADER SECTION -->

changelog/Views/partial/_script.cshtml
<!-- =========================
     SCRIPTS
============================== -->


<script src="~/resources/js/jquery.min.js"></script>
<script src="~/resources/js/bootstrap.min.js"></script>
<script src="~/resources/js/owl.carousel.js"></script>
<script src="~/resources/js/jquery.fitvids.js"></script>
<script src="~/resources/js/smoothscroll.js"></script>
<script src="~/resources/js/jquery.parallax-1.1.3.js"></script>
<script src="~/resources/js/jquery.prettyPhoto.js"></script>
<script src="~/resources/js/jquery.ajaxchimp.min.js"></script>
<script src="~/resources/js/jquery.ajaxchimp.langs.js"></script>
<script src="~/resources/js/wow.min.js"></script>
<script src="~/resources/js/waypoints.min.js"></script>
<script src="~/resources/js/jquery.counterup.min.js"></script>
<script src="~/resources/js/script.js"></script>

changelog/Views/partial/_testimonial.cshtml
@model changelog.Models.ChangeLogModel

<!-- =========================
     START TESTIMONIAL SECTION
============================== -->

<section id="TESTIMONIAL" class="testimonial parallax">
    <div class="section_overlay">
        <div class="container">
            <div class="row">
                <div class="col-md-12 wow bounceInDown">
                    <div id="carousel-example-caption-testimonial" class="carousel slide" data-ride="carousel">

                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            @for (int iLi = 0; iLi <= Model._db_author.Count() - 1; iLi++)
                            {
                                if (@iLi == 0)
                                {
                                    <li data-target="#carousel-example-caption-testimonial" data-slide-to="@iLi" class="active"></li>
                                }
                                else
                                {
                                    <li data-target="#carousel-example-caption-testimonial" data-slide-to="@iLi"></li>
                                }
                            }
                        </ol>
                        @{
                            string sActive = "active";
                        }
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            @foreach (var xrow_author in Model._db_author)
                            {

                                <div class="item @sActive">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-md-12 text-center">
                                                <!-- IMAGE -->
                                                <img src=@Url.Content(xrow_author.AuthorAvatarUrl) alt="">
                                                <div class="testimonial_caption">
                                                    <!-- DESCRIPTION -->
                                                    <h2>@xrow_author.AuthorDisplayName</h2>
                                                    <h4><a target="_blank" href=@Url.Content("mailto:" + xrow_author.AuthorEmailAddress + "?subject=Уважаемая(ый)" + xrow_author.AuthorDisplayName)><span>Написать письмо</span></a> <a target="_blank" href=@Url.Content(xrow_author.AuthorLinks)>Профиль пользователя</a></h4>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                              sActive = "";
                            }
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>







<!-- END TESTIMONIAL SECTION -->